name: Android Release Build

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  android-release:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Make gradlew executable
        run: cd android && chmod +x ./gradlew

      # APK RELEASE (contém o index.android.bundle embutido)
      - name: Build release APK
        run: cd android && ./gradlew assembleRelease

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk

      # AAB RELEASE (para Play Console)
      - name: Build release AAB
        run: cd android && ./gradlew bundleRelease

      - name: Upload release AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: android/app/build/outputs/bundle/release/app-release.aab
