name: 📦 EAS Auto Build on Commit

on:
  push:
    branches:
      - main

jobs:
  eas-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install EAS CLI
        run: npm install -g eas-cli@latest

      # ✅ Autenticação correta via token
      - name: Authenticate with Expo
        run: npx eas whoami || true
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Build Android (Production)
        run: npx eas build --platform android --non-interactive --profile production
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}


      - name: Upload build logs
        uses: actions/upload-artifact@v4
        with:
          name: eas-build-logs
          path: |
            dist
            .eas
            .expo
